Update config.yml trial again8

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,7 +10,7 @@ jobs:
           name: "Say hello"
           command: "echo Hello, World!"
 
-  sonarqube:
+    sonarqube:
     working_directory: ~/build
     docker:
       - image: alpine:latest  # Using Alpine-based image for apk commands
@@ -26,13 +26,16 @@ jobs:
           unzip sonar-scanner-cli.zip -d /usr/local/
           mv /usr/local/sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner
           export PATH=$PATH:/usr/local/sonar-scanner/bin
-      - attach_workspace:
-          at: ~/workspace
-      - run: |
+          
+          # Confirm sonar-scanner installation
+          if ! which sonar-scanner; then
+            echo "Sonar-scanner installation failed" && exit 1
+          fi
+          
           # Run SonarQube scan
           SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
-          echo "Sonar branch value is: " $SONAR_BRANCH
-          echo "Sonar org value is : "$SONAR_ORG
+          echo "Sonar branch value is: $SONAR_BRANCH"
+          echo "Sonar org value is: $SONAR_ORG"
           sonar-scanner \
             -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
             -Dsonar.organization="$SONAR_ORG" \
